{
    'name':'Documental Management',
    'summary':'''
        Documental Management:
        Requirements,
        Settlements,
        Mobility Expediture Worksheet,
    ''',
    'version':'3.1.2',
    'category':'mkt',
    'author':'Aaron Ilizarbe - Marketing Alterno',
    'license': 'AGPL-3',
    'depends':[
        'base',
        'account',
        'mail',
        'hr',
        'web',
        'website',
        'mkt_report_formats',
        'l10n_pe',
        'portal',
        'mkt_cost_center',
        'mkt_res_province',
    ],
    'external_dependencies': {
        'python': ['Pillow', 'img2pdf'],
        'bin': ['soffice'],  # LibreOffice
    },
    'data':[
        'security/security.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',

        'data/ir_sequence_data.xml',
        'data/paperformat_data.xml',
        'data/documental_header_template.xml',
        'data/documental_managment_data.xml',
        'data/mail_data.xml',
        'data/ir_cron.xml',

        'views/years_views.xml',
        'views/budget_views.xml',
        'views/documental_requirements.xml',
        'views/documental_settlements.xml',
        'views/documental_mobility.xml',
        'views/report_administration_views.xml',
        'views/requirement_service_type_views.xml',
        'views/res_partner_views.xml',
        'views/settlement_detail_line_views.xml',
        'views/requirement_detail_line_views.xml',
        'views/tax_taxes_views.xml',
        'views/expenses_control_report_views.xml',
        'views/settlement_detail_views.xml',
        'views/dni_consult_views.xml',
        'views/ruc_consult_views.xml',
        'views/settlement_line_type_views.xml',
        'views/voucher_views.xml',
        'views/change_type.xml',
        'views/budget_class_views.xml',
        'views/campaign_views.xml',
        'views/budget_modify_views.xml',
        'views/cpe_consult_views.xml',
        'views/settlement_line_views.xml',
        'views/settlement_views.xml',
        'views/requirement_detail_views.xml',
        'views/affidavit_views.xml',
        #'views/website_menu.xml',
        'views/months_views.xml',
        'views/portal_templates.xml',
        'views/requirement_payment_views.xml',
        'views/mobility_line_views.xml',
        'views/settlement_update_views.xml',
        'views/brand_views.xml',
        'views/groups_categorys_views.xml',
        'views/user_groups_views.xml',
        'views/hr_employee_views.xml',
        'views/res_bank_views.xml',
        'views/settlement_voucher_last_views.xml',
        'views/announcement_views.xml',
        'views/requirement_province_acl_views.xml',

        'report/documental_requirement_report.xml',
        'report/documental_settlement_report.xml',
        'report/documental_mobility_expediture_report.xml',
        'report/voucher_report.xml',
        'report/affidavit_report.xml',
        'report/ir_actions_report.xml',
        'report/all_reports.xml',

        'wizard/requirement_report_wiz.xml',
        'wizard/expense_control_wiz.xml',
        'wizard/accounting_report_wiz.xml',
        'wizard/pending_settlement_wiz.xml',
        'wizard/return_requirement_confirmation_wiz.xml',
        'wizard/expenses_report_wiz.xml',
        'wizard/requirement_modify.xml',
        'wizard/cash_report.xml',
        'wizard/purchase_report.xml',
        'wizard/settlement_report_wiz.xml',
        'wizard/bank_report.xml',
        'wizard/mobility_report.xml',
        'wizard/accounting_expenses_report_wiz.xml',
        'wizard/province_report_wiz.xml',
        'wizard/province_reimbursements_report_views.xml',

        'views/menu_view.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'mkt_documental_managment/static/src/js/affidavit.js',
        ],
    },
    'installable':True,
    'auto_install':False,
    'application': True,
}